name: Junit Results
description: Parse JUnit results
author: Michael Stringer

inputs:
  files:
    description: Glob pattern to match JUnit files
    required: true
  upload-results:
    description: If true then upload an artifact with a summary of the results
    required: false
    default: 'true'
  artifact-name:
    description: Name of the artifact to store test results in
    required: false

runs:
  using: node16
  main: dist/index.js