name: Junit Results
description: Parse JUnit results
author: Michael Stringer

inputs:
  files:
    description: Glob pattern to match JUnit files
    required: true
  store-summary:
    description: If true then upload an artifact with a summary of the results
    required: false
    default: 'false'

runs:
  using: node16
  main: index.js