name: Junit Results
description: Parse JUnit results
author: Michael Stringer

inputs:
  files:
    description: Glob pattern to match JUnit files
    required: true
  upload-report:
    description: If true then upload an HTML report
    required: false
    default: 'true'
  artifact-name:
    description: Name of the artifact to store HTML report in
    required: false

runs:
  using: node16
  main: dist/index.js