name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.tag_name}}

      - run: npm ci
      - run: npm run build

      - uses: mheap/build-and-tag-action@add-additional-files
        with:
          additional_files: dist/report.ejs
        env:
          GITHUB_TOKEN: ${{github.token}}
